// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDITQKM-i7z1Xe6C6nQoIDbTf1oL8qJD80',
    appId: '1:272081098069:web:195738987cac91fc200bdc',
    messagingSenderId: '272081098069',
    projectId: 'solemate-61830',
    authDomain: 'solemate-61830.firebaseapp.com',
    storageBucket: 'solemate-61830.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFuKMMCCloWnxYtjiyMSbjHMLncFDnM3M',
    appId: '1:272081098069:android:cadf968f3eb77c9e200bdc',
    messagingSenderId: '272081098069',
    projectId: 'solemate-61830',
    storageBucket: 'solemate-61830.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzjkcag9QAdQWpLpx0Ks254DZNQjEEuYM',
    appId: '1:272081098069:ios:440e1ac75b2e7e8f200bdc',
    messagingSenderId: '272081098069',
    projectId: 'solemate-61830',
    storageBucket: 'solemate-61830.firebasestorage.app',
    iosBundleId: 'com.example.solemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzjkcag9QAdQWpLpx0Ks254DZNQjEEuYM',
    appId: '1:272081098069:ios:440e1ac75b2e7e8f200bdc',
    messagingSenderId: '272081098069',
    projectId: 'solemate-61830',
    storageBucket: 'solemate-61830.firebasestorage.app',
    iosBundleId: 'com.example.solemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDITQKM-i7z1Xe6C6nQoIDbTf1oL8qJD80',
    appId: '1:272081098069:web:34e82597bb9e8769200bdc',
    messagingSenderId: '272081098069',
    projectId: 'solemate-61830',
    authDomain: 'solemate-61830.firebaseapp.com',
    storageBucket: 'solemate-61830.firebasestorage.app',
  );
}
